const COUNTRIES = [
  { code: 'AF', name_ru: 'Афганистан' },
  { code: 'AX', name_ru: 'Острова Аландские' },
  { code: 'AL', name_ru: 'Албания' },
  { code: 'DZ', name_ru: 'Алжир' },
  { code: 'AS', name_ru: 'Американское Самоа' },
  { code: 'AD', name_ru: 'Андорра' },
  { code: 'AO', name_ru: 'Ангола' },
  { code: 'AI', name_ru: 'Ангилья' },
  { code: 'AQ', name_ru: 'Антарктида' },
  { code: 'AG', name_ru: 'Антигуа и Барбуда' },
  { code: 'AR', name_ru: 'Аргентина' },
  { code: 'AM', name_ru: 'Армения' },
  { code: 'AW', name_ru: 'Аруба' },
  { code: 'AU', name_ru: 'Австралия' },
  { code: 'AT', name_ru: 'Австрия' },
  { code: 'AZ', name_ru: 'Азербайджан' },
  { code: 'BS', name_ru: 'Багамы' },
  { code: 'BH', name_ru: 'Бахрейн' },
  { code: 'BD', name_ru: 'Бангладеш' },
  { code: 'BB', name_ru: 'Барбадос' },
  { code: 'BY', name_ru: 'Беларусь' },
  { code: 'BE', name_ru: 'Бельгия' },
  { code: 'BZ', name_ru: 'Белиз' },
  { code: 'BJ', name_ru: 'Бенин' },
  { code: 'BM', name_ru: 'Бермуды' },
  { code: 'BT', name_ru: 'Бутан' },
  { code: 'BO', name_ru: 'Боливия (Многонациональное Государство Боливия)' },
  { code: 'BQ', name_ru: 'Бонайре, Синт-Эстатиус и Саба' },
  { code: 'BA', name_ru: 'Босния и Герцеговина' },
  { code: 'BW', name_ru: 'Ботсвана' },
  { code: 'BV', name_ru: 'Остров Буве' },
  { code: 'BR', name_ru: 'Бразилия' },
  { code: 'IO', name_ru: 'Британская территория в Индийском океане' },
  { code: 'BN', name_ru: 'Бруней-Даруссалам' },
  { code: 'BG', name_ru: 'Болгария' },
  { code: 'BF', name_ru: 'Буркина-Фасо' },
  { code: 'BI', name_ru: 'Бурунди' },
  { code: 'CV', name_ru: 'Кабо-Верде' },
  { code: 'KH', name_ru: 'Камбоджа' },
  { code: 'CM', name_ru: 'Камерун' },
  { code: 'CA', name_ru: 'Канада' },
  { code: 'KY', name_ru: 'Каймановы острова' },
  { code: 'CF', name_ru: 'Центральноафриканская Республика' },
  { code: 'TD', name_ru: 'Чад' },
  { code: 'CL', name_ru: 'Чили' },
  { code: 'CN', name_ru: 'Китай' },
  { code: 'CX', name_ru: 'Остров Рождества' },
  { code: 'CC', name_ru: 'Кокосовые (Килинг) острова' },
  { code: 'CO', name_ru: 'Колумбия' },
  { code: 'KM', name_ru: 'Коморы' },
  { code: 'CD', name_ru: 'Демократическая Республика Конго' },
  { code: 'CG', name_ru: 'Конго' },
  { code: 'CK', name_ru: 'Острова Кука' },
  { code: 'CR', name_ru: 'Коста-Рика' },
  { code: 'CI', name_ru: 'Кот-д’Ивуар' },
  { code: 'HR', name_ru: 'Хорватия' },
  { code: 'CU', name_ru: 'Куба' },
  { code: 'CW', name_ru: 'Кюрасао' },
  { code: 'CY', name_ru: 'Кипр' },
  { code: 'CZ', name_ru: 'Чехия' },
  { code: 'DK', name_ru: 'Дания' },
  { code: 'DJ', name_ru: 'Джибути' },
  { code: 'DM', name_ru: 'Доминика' },
  { code: 'DO', name_ru: 'Доминиканская Республика' },
  { code: 'EC', name_ru: 'Эквадор' },
  { code: 'EG', name_ru: 'Египет' },
  { code: 'SV', name_ru: 'Сальвадор' },
  { code: 'GQ', name_ru: 'Экваториальная Гвинея' },
  { code: 'ER', name_ru: 'Эритрея' },
  { code: 'EE', name_ru: 'Эстония' },
  { code: 'SZ', name_ru: 'Эсватини' },
  { code: 'ET', name_ru: 'Эфиопия' },
  { code: 'FK', name_ru: 'Фолклендские острова (Мальвинские)' },
  { code: 'FO', name_ru: 'Фарерские острова' },
  { code: 'FJ', name_ru: 'Фиджи' },
  { code: 'FI', name_ru: 'Финляндия' },
  { code: 'FR', name_ru: 'Франция' },
  { code: 'GF', name_ru: 'Французская Гвиана' },
  { code: 'PF', name_ru: 'Французская Полинезия' },
  { code: 'TF', name_ru: 'Французские Южные и Антарктические Территории' },
  { code: 'GA', name_ru: 'Габон' },
  { code: 'GM', name_ru: 'Гамбия' },
  { code: 'GE', name_ru: 'Грузия' },
  { code: 'DE', name_ru: 'Германия' },
  { code: 'GH', name_ru: 'Гана' },
  { code: 'GI', name_ru: 'Гибралтар' },
  { code: 'GR', name_ru: 'Греция' },
  { code: 'GL', name_ru: 'Гренландия' },
  { code: 'GD', name_ru: 'Гренада' },
  { code: 'GP', name_ru: 'Гваделупа' },
  { code: 'GU', name_ru: 'Гуам' },
  { code: 'GT', name_ru: 'Гватемала' },
  { code: 'GG', name_ru: 'Гернси' },
  { code: 'GN', name_ru: 'Гвинея' },
  { code: 'GW', name_ru: 'Гвинея-Бисау' },
  { code: 'GY', name_ru: 'Гайана' },
  { code: 'HT', name_ru: 'Гаити' },
  { code: 'HM', name_ru: 'Острова Херд и Макдональд' },
  { code: 'VA', name_ru: 'Ватикан' },
  { code: 'HN', name_ru: 'Гондурас' },
  { code: 'HK', name_ru: 'Гонконг (САР Китай)' },
  { code: 'HU', name_ru: 'Венгрия' },
  { code: 'IS', name_ru: 'Исландия' },
  { code: 'IN', name_ru: 'Индия' },
  { code: 'ID', name_ru: 'Индонезия' },
  { code: 'IR', name_ru: 'Иран (Исламская Республика)' },
  { code: 'IQ', name_ru: 'Ирак' },
  { code: 'IE', name_ru: 'Ирландия' },
  { code: 'IM', name_ru: 'Остров Мэн' },
  { code: 'IL', name_ru: 'Израиль' },
  { code: 'IT', name_ru: 'Италия' },
  { code: 'JM', name_ru: 'Ямайка' },
  { code: 'JP', name_ru: 'Япония' },
  { code: 'JE', name_ru: 'Джерси' },
  { code: 'JO', name_ru: 'Иордания' },
  { code: 'KZ', name_ru: 'Казахстан' },
  { code: 'KE', name_ru: 'Кения' },
  { code: 'KI', name_ru: 'Кирибати' },
  { code: 'KP', name_ru: 'КНДР (Корейская Народно-Демократическая Республика)' },
  { code: 'KR', name_ru: 'Республика Корея' },
  { code: 'KW', name_ru: 'Кувейт' },
  { code: 'KG', name_ru: 'Киргизия' },
  { code: 'LA', name_ru: 'Лаосская Народно-Демократическая Республика' },
  { code: 'LV', name_ru: 'Латвия' },
  { code: 'LB', name_ru: 'Ливан' },
  { code: 'LS', name_ru: 'Лесото' },
  { code: 'LR', name_ru: 'Либерия' },
  { code: 'LY', name_ru: 'Ливия' },
  { code: 'LI', name_ru: 'Лихтенштейн' },
  { code: 'LT', name_ru: 'Литва' },
  { code: 'LU', name_ru: 'Люксембург' },
  { code: 'MO', name_ru: 'Макао (САР Китай)' },
  { code: 'MG', name_ru: 'Мадагаскар' },
  { code: 'MW', name_ru: 'Малави' },
  { code: 'MY', name_ru: 'Малайзия' },
  { code: 'MV', name_ru: 'Мальдивы' },
  { code: 'ML', name_ru: 'Мали' },
  { code: 'MT', name_ru: 'Мальта' },
  { code: 'MH', name_ru: 'Маршалловы Острова' },
  { code: 'MQ', name_ru: 'Мартинника' },
  { code: 'MR', name_ru: 'Мавритания' },
  { code: 'MU', name_ru: 'Маврикий' },
  { code: 'YT', name_ru: 'Майотта' },
  { code: 'MX', name_ru: 'Мексика' },
  { code: 'FM', name_ru: 'Микронезия (Федеративные Штаты)' },
  { code: 'MD', name_ru: 'Молдова (Республика)' },
  { code: 'MC', name_ru: 'Монако' },
  { code: 'MN', name_ru: 'Монголия' },
  { code: 'ME', name_ru: 'Черногория' },
  { code: 'MS', name_ru: 'Монтсеррат' },
  { code: 'MA', name_ru: 'Марокко' },
  { code: 'MZ', name_ru: 'Мозамбик' },
  { code: 'MM', name_ru: 'Мьянма' },
  { code: 'NA', name_ru: 'Намибия' },
  { code: 'NR', name_ru: 'Науру' },
  { code: 'NP', name_ru: 'Непал' },
  { code: 'NL', name_ru: 'Нидерланды' },
  { code: 'NC', name_ru: 'Новая Каледония' },
  { code: 'NZ', name_ru: 'Новая Зеландия' },
  { code: 'NI', name_ru: 'Никарагуа' },
  { code: 'NE', name_ru: 'Нигер' },
  { code: 'NG', name_ru: 'Нигерия' },
  { code: 'NU', name_ru: 'Ниуэ' },
  { code: 'NF', name_ru: 'Остров Норфолк' },
  { code: 'MK', name_ru: 'Северная Македония' },
  { code: 'MP', name_ru: 'Северные Марианские острова' },
  { code: 'NO', name_ru: 'Норвегия' },
  { code: 'OM', name_ru: 'Оман' },
  { code: 'PK', name_ru: 'Пакистан' },
  { code: 'PW', name_ru: 'Палау' },
  { code: 'PS', name_ru: 'Палестинские территории, оккупированные' },
  { code: 'PA', name_ru: 'Панама' },
  { code: 'PG', name_ru: 'Папуа — Новая Гвинея' },
  { code: 'PY', name_ru: 'Парагвай' },
  { code: 'PE', name_ru: 'Перу' },
  { code: 'PH', name_ru: 'Филиппины' },
  { code: 'PN', name_ru: 'Острова Питкэрн' },
  { code: 'PL', name_ru: 'Польша' },
  { code: 'PT', name_ru: 'Португалия' },
  { code: 'PR', name_ru: 'Пуэрто-Рико' },
  { code: 'QA', name_ru: 'Катар' },
  { code: 'RE', name_ru: 'Реюньон' },
  { code: 'RO', name_ru: 'Румыния' },
  { code: 'RU', name_ru: 'Россия' },
  { code: 'RW', name_ru: 'Руанда' },
  { code: 'BL', name_ru: 'Сен-Бартелеми' },
  { code: 'SH', name_ru: 'Остров Святой Елены, Вознесения и Тристан-да-Кунья' },
  { code: 'KN', name_ru: 'Сент-Китс и Невис' },
  { code: 'LC', name_ru: 'Сент-Люсия' },
  { code: 'MF', name_ru: 'Сен-Мартен (французская часть)' },
  { code: 'PM', name_ru: 'Сен-Пьер и Микелон' },
  { code: 'VC', name_ru: 'Сент-Винсент и Гренадины' },
  { code: 'WS', name_ru: 'Самоа' },
  { code: 'SM', name_ru: 'Сан-Марино' },
  { code: 'ST', name_ru: 'Сан-Томе и Принсипи' },
  { code: 'SA', name_ru: 'Саудовская Аравия' },
  { code: 'SN', name_ru: 'Сенегал' },
  { code: 'RS', name_ru: 'Сербия' },
  { code: 'SC', name_ru: 'Сейшельские Острова' },
  { code: 'SL', name_ru: 'Сьерра-Леоне' },
  { code: 'SG', name_ru: 'Сингапур' },
  { code: 'SX', name_ru: 'Синт-Мартен (нидерландская часть)' },
  { code: 'SK', name_ru: 'Словакия' },
  { code: 'SI', name_ru: 'Словения' },
  { code: 'SB', name_ru: 'Соломоновы Острова' },
  { code: 'SO', name_ru: 'Сомали' },
  { code: 'ZA', name_ru: 'Южно-Африканская Республика' },
  { code: 'GS', name_ru: 'Южная Георгия и Южные Сандвичевы Острова' },
  { code: 'SS', name_ru: 'Южный Судан' },
  { code: 'ES', name_ru: 'Испания' },
  { code: 'LK', name_ru: 'Шри-Ланка' },
  { code: 'SD', name_ru: 'Судан' },
  { code: 'SR', name_ru: 'Суринам' },
  { code: 'SJ', name_ru: 'Шпицберген и Ян-Майен' },
  { code: 'SE', name_ru: 'Швеция' },
  { code: 'CH', name_ru: 'Швейцария' },
  { code: 'SY', name_ru: 'Сирийская Арабская Республика' },
  { code: 'TW', name_ru: 'Тайвань (Китай)' },
  { code: 'TJ', name_ru: 'Таджикистан' },
  { code: 'TZ', name_ru: 'Танзания, Объединенная Республика' },
  { code: 'TH', name_ru: 'Таиланд' },
  { code: 'TL', name_ru: 'Тимор-Лесте' },
  { code: 'TG', name_ru: 'Того' },
  { code: 'TK', name_ru: 'Токелау' },
  { code: 'TO', name_ru: 'Тонга' },
  { code: 'TT', name_ru: 'Тринидад и Тобаго' },
  { code: 'TN', name_ru: 'Тунис' },
  { code: 'TR', name_ru: 'Турция' },
  { code: 'TM', name_ru: 'Туркменистан' },
  { code: 'TC', name_ru: 'Острова Тёркс и Кайкос' },
  { code: 'TV', name_ru: 'Тувалу' },
  { code: 'UG', name_ru: 'Уганда' },
  { code: 'UA', name_ru: 'Украина' },
  { code: 'AE', name_ru: 'Объединённые Арабские Эмираты' },
  { code: 'GB', name_ru: 'Великобритания' },
  { code: 'US', name_ru: 'Соединённые Штаты' },
  { code: 'UM', name_ru: 'Малые отдалённые острова США' },
  { code: 'UY', name_ru: 'Уругвай' },
  { code: 'UZ', name_ru: 'Узбекистан' },
  { code: 'VU', name_ru: 'Вануату' },
  { code: 'VE', name_ru: 'Венесуэла (Боливарианская Республика)' },
  { code: 'VN', name_ru: 'Вьетнам' },
  { code: 'VG', name_ru: 'Виргинские острова (Британские)' },
  { code: 'VI', name_ru: 'Виргинские острова (США)' },
  { code: 'WF', name_ru: 'Уоллис и Футуна' },
  { code: 'EH', name_ru: 'Западная Сахара' },
  { code: 'YE', name_ru: 'Йемен' },
  { code: 'ZM', name_ru: 'Замбия' },
  { code: 'ZW', name_ru: 'Зимбабве' }
] as const

export { COUNTRIES }
